FROM php:8.0
RUN apt-get update
RUN  apt-get -y install php-pgsql
RUN apt-get -y install libapache2-mod-php
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql
FROM python:3.10
RUN pip install --upgrade pip
RUN pip install Flask==2.2.2
RUN pip install flask_socketio==4.3.1
RUN pip install matplotlib==3.6.2
RUN pip install mtcnn==0.1.1
RUN pip install numpy==1.23.5
RUN pip install opencv-python
RUN pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-2.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
RUN pip install opencv-python-headless==4.6.0.66
RUN pip install Pillow==9.3.0
RUN pip install tqdm==4.64.1
ENV STATIC_URL /static
ENV STATIC_PATH /static
ENV TEMPLATES_URL /templates
ENV TEMPLATES_PATH /templates
COPY app.py /app.py
CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]