FROM php:8.1
RUN apt-get update
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql
FROM python:3.10
RUN pip install --upgrade pip
RUN pip install Flask==2.2.2
RUN pip install flask_socketio==4.3.1
RUN pip install matplotlib==3.6.2
RUN pip install mtcnn==0.1.1
RUN pip install numpy==1.23.5
RUN pip install opencv-python
RUN pip install tensorflow --user
RUN pip install opencv-python-headless==4.6.0.66
RUN pip install Pillow==9.3.0
RUN pip install tqdm==4.64.1
COPY app.py /app.py
EXPOSE 8080
CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]